development:
  adapter: postgresql
  encoding: unicode
  database: scrabble_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: scrabble_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: scrabble_production
  pool: 5
  username: postgres
  password: postgres
