development:
  adapter: postgresql
  encoding: unicode
  database: scrabble_development
  pool: 5
  username: your_username
  password: your_password

test:
  adapter: postgresql
  encoding: unicode
  database: scrabble_test
  pool: 5
  username: your_username
  password: your_password

production:
  adapter: postgresql
  encoding: unicode
  database: scrabble_production
  pool: 5
  username: your_username
  password: your_password
